name: Continuous Deployment

on:
  workflow_dispatch

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - uses: actions/setup-node@v1
      with:
        node-version: 16

    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - run: npm install
      if: steps.cache.outputs.cache-hit != 'true'

    - run: npm run compile

    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: compile

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - uses: actions/setup-node@v1
      with:
        node-version: 16

    - uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - uses: actions/download-artifact@v2
      with:
        name: build
        path: dist

    - run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > $SSH_KEY_PATH
        sudo chmod 600 $SSH_KEY_PATH
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        SSH_KEY_PATH: ${{ github.workspace }}/../private.key

    - run: |
        scp -i $SSH_KEY_PATH -r dist root@0.0.0.0:~/
        scp -i $SSH_KEY_PATH package.json package-lock.json root@0.0.0.0:~/dist
      env:
        SSH_KEY_PATH: ${{ github.workspace }}/../private.key

    - run: |
        ssh -tti $SSH_KEY_PATH root@0.0.0.0 << EOF
          cp -R ~/dist/* /app/hypegienic-api \
          && rm -rf ~/dist/ \
          && cd /app/hypegienic-api \
          && npm install \
          && pm2 reload hypegienic-api \
          && exit
        EOF
      env:
        SSH_KEY_PATH: ${{ github.workspace }}/../private.key

    - run: exit $?
