name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - uses: actions/setup-node@v1
      with:
        node-version: 16

    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - run: npm install
      if: steps.cache.outputs.cache-hit != 'true'

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    services:
      neo4j:
        image: neo4j:4.1.1
        ports:
        - 7474:7474
        - 7687:7687
        env:       
          NEO4J_AUTH: test/testing123
          NEO4J_dbms_connector_bolt_advertised__address: localhost:7687
        options:
          --health-cmd "cypher-shell 'match (n) return count(n)'"
          --health-timeout 10s
          --health-retries 20
          --health-interval 10s
          --health-start-period 30s

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - uses: actions/setup-node@v1
      with:
        node-version: 16

    - uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - run: npm test
